spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mpdemo?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root


logging:
  level:
    root: info
    com.lpl.mpdemo.mapper: trace
  pattern:
    console: '%p%m%n'


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml